opname: "BCa_PDXs"
metadatafile: /cluster/projects/bhklab/projects/BCaATAC/BCa_ARCHE_Scoring/metadata/pdx_metadata.txt
consensusfile: /cluster/projects/bhklab/projects/BCaATAC/BCa_ARCHE_Scoring/data/results/PDXs/consensus/PeakCalls_unionPeakSet.bed
PEAKS_DIR: /cluster/projects/bhklab/projects/BCaATAC/BCa_ARCHE_Scoring/data/rawdata/PDXs/filtered_narrowpeak/
peaks_extension: "_peaks.filtered.narrowPeak"
hg38TEs_DIR: /cluster/projects/bhklab/projects/BCaATAC/BCa_ARCHE_Scoring/data/procdata/ARCHEs/20k_sites/
hg38TEs_extension: ".bed"
qval: 0.01